package com.datasoft.luncheon.kpi;

import com.datasoft.luncheon.commons.model.filter.SingleFilter;
import lombok.Data;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;

@Data
public class KpiConfigParams {
    private Integer userId;
    private String userIdKPI;
    private Integer pid;
    private String pname;
    private String userName;
    private String description;
    private String objectId;
    private String component;
    private String fieldName;
    private String excludeParam;
//    private List<SingleFilter> filterParam;
//    private List<SingleFilter> transactionFilterParam;
    private String searchParam;
    private String selectedIds;
    private String selectedRegionIds;
    private String orderParam;
    private String orderType;
    private Integer paramLimit;
    private Integer paramOffset;
    private Boolean paramStatus;
    private String initiatorType;
    private String photoId;
    private String accountNumber;
    private String parameter;
    private String dhMasterAcctNumber;
    private String dhAccountNumber;
    private String dsoAccountNumber;
    private String dsoAcctNumber;
    private String accountType;
    private String assesseeType;
    private String existedRoleName;
    private String roleName;
    private String startDate;
    private String endDate;
    private String startTime;
    private String endTime;
    private String status;
    private String date;
    private String recommendationId;
    private String param;
    private String pType;
    private String transactionType;
    private Integer resultIndx;
    private String sequenceOfList;
    private String reason;
    private String objectType;
    private String id;
    private String eddRecord;
    private Integer caoId;
    private String remarks;
    private Integer totalRow;
    private String queryType;
    private String customSessionId;
    private String queryString;
    private Integer crIssueId;
    private Integer crId;
    private String tableId;
    private String generatedId;
    private String executedDate;
    private String frequency;
    private String previousfrequency;
    private String numOfDay;
    private String extraParam;
    private String ids;
    private Boolean objStatus;
    private String notificationData;
    private MultipartFile file;
    private String requestType;
    private Integer pcrIssueId;
    private Integer productSegmentId;
    private String employeeType;
    private String module;
    private String section;
    private Integer trpId;
    private String otherParam;
    private String remark;
    private Integer deployedById;
    private Integer issueId;
    private String regionName;
    private String region;
    private String createdBy;
    private Integer year;
    private Map<String, Object> fcaData;
    private Map<String, Object> approver;
//    private Map<String, Object> randomData;
    private String objectiveData;
    private String selfData;
    private String valuesData;
    private String managerData;
    private String hrData;
    private String randomData;
    private String hierarchyData;
    private Map<String, Object> oldTotal;
    private String questionVersion;

    private String fcaType;
    private List<String> risks;
    private List<String> regionList;
    private List<String> dhName;
    private List<String> areas;
    private Integer fcaRequestId;
    private List<String> cao;
    private String risk;
    private String area;
    private String dhAccounts;
    private String type;
    private String sessionId;
    private double lat;
    private double endingLat;
    private double lon;
    private double endingLon;
    private String source;
    private String clientId;
    private int page;
    private String walletList;
    private String team;
    private Integer category;

    public List<SingleFilter> filterParam;
}
